name: 打包成EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v5

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: 打包为单文件EXE
        run: pyinstaller -F --add-data "1.jpg;." source_integrator.py

      - name: 上传EXE成品
        uses: actions/upload-artifact@v4
        with:
          name: 打包好的程序
          path: dist/*.exe
