name: 多平台打包

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      
      - name: 安装依赖
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install pyinstaller
        shell: bash
      
      - name: 打包程序
        run: pyinstaller -F 你的文件名.py
      
      - uses: actions/upload-artifact@v4
        with:
          name: 程序-${{ matrix.os }}
          path: dist/*
